In [ ]:
#%pip install sentence-transformers

import os
from dotenv import load_dotenv
load_dotenv(override=True, dotenv_path="../.env.local")
my_api_key = os.getenv("OPENAI_API_KEY")



In [4]:

# select * from table where text like '%internet%'

# What’s the internet usage policy?

# Step 1: Define Sample Documents
# Document Corpus
documents = [
    {"doc_id": "1", "section": "Pay Policies", "content": "Employees are paid bi-weekly via direct deposit."},
    {"section": "Leave of Absence", "content": "Employees must submit a leave request for approval."},
    # query = "What’s the internet usage policy?"
    {"section": "Internet Use", "content": "Company internet must be used for work-related tasks only."},
    {"section": "Internet Use", "content": "Company internet is a broadband internet."},
    {"section": "Break at Work", "content": "Employees can take an hour break."},
    {"section": "Harassment", "content": "Interact with each employee with Respect"}
]

# Step 2: Get Content Texts
content_corpus = [doc["content"] for doc in documents]

content_corpus

['Employees are paid bi-weekly via direct deposit.',
 'Employees must submit a leave request for approval.',
 'Company internet must be used for work-related tasks only.',
 'Company internet is a broadband internet.',
 'Employees can take an hour break.',
 'Interact with each employee with Respect']

In [ ]:
#import sentence_transformers
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
doc_vectors = model.encode(content_corpus)
#doc_vectors[0]

array([ 2.47251354e-02, -9.08146240e-03,  3.88712734e-02,  3.23015004e-02,
       -5.89054786e-02,  3.91246565e-02,  2.60180123e-02, -4.36909236e-02,
       -1.91601142e-02, -1.10987514e-06,  1.36534311e-02,  4.32674447e-03,
       -5.37855886e-02,  6.86896592e-03,  7.63820857e-03, -6.06964082e-02,
       -3.76022197e-02,  7.14091118e-03,  1.33871749e-01,  1.73536362e-03,
       -3.07555520e-03, -7.78130144e-02, -8.45143795e-02, -3.21636279e-03,
        1.33828014e-01, -3.64357978e-02,  1.69227943e-02,  4.86148149e-02,
       -4.02879752e-02,  1.96767263e-02, -4.37128879e-02,  5.15113957e-02,
       -1.62995793e-02, -3.90591882e-02, -4.45387419e-03,  4.74460074e-04,
       -3.12051810e-02,  4.89561930e-02,  1.28317317e-02,  1.59401577e-02,
       -4.75851372e-02, -1.72242653e-02,  2.29330733e-02, -7.40373135e-02,
       -1.08638905e-01,  3.75389238e-03,  2.24708039e-02,  9.03265327e-02,
       -7.93716088e-02,  1.15316518e-01,  7.89923295e-02, -8.36823285e-02,
        7.83054605e-02,  

In [24]:
doc_vectors

array([[ 0.02472514, -0.00908146,  0.03887127, ...,  0.01965653,
         0.04260012, -0.0270714 ],
       [ 0.033155  ,  0.04853383,  0.04736271, ...,  0.1018201 ,
         0.09159277,  0.00358373],
       [-0.07135907, -0.03066471,  0.03183774, ..., -0.04109804,
         0.06524776, -0.00688534],
       [-0.00383737, -0.02336752,  0.02958675, ..., -0.04415287,
         0.12559088, -0.03139851],
       [-0.01790444,  0.01495846,  0.08163834, ..., -0.03217231,
        -0.00513649,  0.05279536],
       [-0.00240887,  0.03361158, -0.06162646, ...,  0.0483088 ,
         0.03707636, -0.01683049]], shape=(6, 384), dtype=float32)

In [7]:
# Step 3: User Query and Semantic Matching

query = "What’s the internet usage policy?"
query_vec = model.encode([query])[0]
query_vec


array([ 2.39821128e-03, -4.11839746e-02, -2.52490789e-02, -4.67050113e-02,
        4.32102988e-03,  1.65876392e-02,  1.20891653e-01, -3.50352973e-02,
        2.16828170e-03, -1.62915225e-04,  2.62876172e-02,  9.05027986e-02,
       -2.66066231e-02, -1.82131752e-02,  3.06278076e-02,  1.67854819e-02,
        1.55614484e-02, -8.26498196e-02, -3.40456627e-02, -3.08671407e-02,
        7.89995044e-02, -3.16904373e-02,  1.35831200e-02,  9.12277610e-04,
       -1.05809495e-02,  3.91190909e-02, -3.48707587e-02,  8.63989262e-05,
       -3.52702774e-02,  3.56902778e-02,  9.55276005e-03, -3.57899368e-02,
        4.84952191e-03, -4.10226583e-02, -7.66861811e-02, -1.00646794e-01,
       -9.23561081e-02, -2.47275201e-03, -2.74320990e-02,  2.85045840e-02,
        2.86295861e-02, -7.78359324e-02, -2.46459898e-03,  9.98250544e-02,
        5.86107038e-02,  2.24836636e-02,  1.56593247e-04,  1.44218272e-02,
        5.55927865e-04,  3.22429687e-02,  1.03300050e-01,  3.42919789e-02,
        3.94683443e-02,  

In [25]:
similarities = model.similarity(query_vec, doc_vectors)

# Ensure it's a 1D numpy array
import numpy as np
similarities = np.asarray(similarities).squeeze()
similarities

array([0.12655613, 0.09747535, 0.4475531 , 0.47982496, 0.11316209,
       0.04429514], dtype=float32)

In [9]:
# Now get top 3
top_3_indices = np.argsort(similarities)[::-1][:3]
print(top_3_indices)
top_scores = similarities[top_3_indices]
top_scores

[3 2 0]


array([0.47982496, 0.4475531 , 0.12655613], dtype=float32)

In [10]:
top_scores

array([0.47982496, 0.4475531 , 0.12655613], dtype=float32)

In [11]:
top_docs = [documents[i]['content'] for i in top_3_indices]
documents = [
     {"section": "Pay Policies", "content": "Employees are paid bi-weekly via direct deposit."},
     {"section": "Leave of Absence", "content": "Employees must submit a leave request for approval."},
     {"section": "Internet Use", "content": "Company internet must be used for work-related tasks only."},
     {"section": "Break at Work", "content": "Employees can take an hour break."},
     {"section": "Harassment", "content": "Interact with each employee with Respect"}
 ]

print (top_docs)
context = ", ".join(top_docs)
context



['Company internet is a broadband internet.', 'Company internet must be used for work-related tasks only.', 'Employees are paid bi-weekly via direct deposit.']


'Company internet is a broadband internet., Company internet must be used for work-related tasks only., Employees are paid bi-weekly via direct deposit.'

In [26]:
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv(override=True, dotenv_path="../.env.local")
my_api_key = os.getenv("OPENAI_API_KEY")

my_client = OpenAI(api_key=my_api_key)
# my_client

def ask_question_open_ai(prompt):

    # print(f"User asked: {prompt}")
    # my_client.chat.completions.create

    llm_response = my_client.chat.completions.create(
        model="gpt-5-nano",
        # messages=[
        #     {"role": "system", "content": "You are a helpful assistant. Answer as concisely as possible."},
        #     {"role": "user", "content": prompt}
        # ]
        messages=[
            {"role": "system", "content": '''
             You are an assistant who answers only based on the given context.
             '''},
            {"role": "user", "content": f"Context: {context}\n\n User Question: {query}"} 
        ]

    )
    return llm_response.choices[0].message.content  

In [27]:
print(query)
response = ask_question_open_ai(query)

What’s the internet usage policy?


In [28]:
print(f"User query: {query}")
print(f"Context: {context}")

print(f"\n\nOpen AI Response: {response}")

User query: What’s the internet usage policy?
Context: Company internet is a broadband internet., Company internet must be used for work-related tasks only., Employees are paid bi-weekly via direct deposit.


Open AI Response: The policy states that the company internet is broadband and must be used for work-related tasks only.


In [ ]:
#Reference Data
expected_answer="The company's internet must be used for work-related tasks only."    
actual_response=response

# Call ChatCompltions API to compare expected vs actual
#LLM AS A JUDGE
comparison_prompt = f"""
You are an expert evaluator. Compare the actual response to the expected answer and determine if they match in meaning.
Expected Answer: {expected_answer}
Actual Response: {actual_response}
Do they match in meaning? Answer with 'Yes' or 'No' and provide a brief explanation.
"""
comparison_response = my_client.chat.completions.create(
    model="gpt-5-nano",     
    messages=[
        {"role": "system", "content": "You are an expert evaluator."},
        {"role": "user", "content": comparison_prompt}
    ]
)   
 



Comparison_response: Yes. The core meaning matches: company internet use is restricted to work-related tasks. The actual adds the extra detail "is broadband," which is not in the expected but does not change the policy’s core meaning.
